substitutions:
  _ENV: dev
  _REGION: us-central1
  _IMAGE_TAG: latest
  _REPOSITORY: artinbk-${_ENV}-containers
  _BACKEND_SERVICE: artinbk-${_ENV}-backend
  _FRONTEND_SERVICE: artinbk-${_ENV}-frontend
  _RUN_MIGRATIONS: "false"
  _BACKEND_URL: "https://replace-with-backend-url"
  _FRONTEND_URL: "https://replace-with-frontend-url"
  _HEALTH_PATH: "/health"
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'backend:build'
    args:
      ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${_IMAGE_TAG}', '-f', 'backend/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'frontend:build'
    args:
      ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${_IMAGE_TAG}', '-f', 'frontend/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'backend:push'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${_IMAGE_TAG}']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'frontend:push'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${_IMAGE_TAG}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy:backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services update ${_BACKEND_SERVICE} \
          --platform=managed \
          --region=${_REGION} \
          --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${_IMAGE_TAG}
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy:frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services update ${_FRONTEND_SERVICE} \
          --platform=managed \
          --region=${_REGION} \
          --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${_IMAGE_TAG}
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'migrate'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${RUN_MIGRATIONS}" != "true" ]]; then
          echo "Skipping migrations; set _RUN_MIGRATIONS=true to enable";
          exit 0;
        fi
        gcloud run jobs deploy ${_BACKEND_SERVICE}-migrate \
          --platform=managed \
          --region=${_REGION} \
          --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${_IMAGE_TAG} \
          --tasks=1 \
          --max-retries=1 \
          --set-secrets=envs=backend-env-${_ENV}:latest
        gcloud run jobs execute ${_BACKEND_SERVICE}-migrate --region=${_REGION} --wait
    env:
      - "RUN_MIGRATIONS=${_RUN_MIGRATIONS}"
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'smoke:backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -f "${_BACKEND_URL}${_HEALTH_PATH}";
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'smoke:frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -f "${_FRONTEND_URL}"
options:
  logging: CLOUD_LOGGING_ONLY
